apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: custom-app
  template:
    metadata:
      labels:
        app: custom-app
    spec:
      containers:
        - name: custom-app-container
          image: vinayakmajhi/vinayak-dockerhub:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
